export const CREATE_TRANSACTION_THUMBNAIL = "ADD_TRANSACTION_THUMBNAIL";
export const UPDATE_TRANSACTION_THUMBNAIL = "UPDATE_TRANSACTION_THUMBNAIL";
export const DELETE_TRANSACTION_THUMBNAIL = "DELETE_TRANSACTION_THUMBNAIL";
export const SET_TRANSACTION_THUMBNAILS = 'SET_TRANSACTION_THUMBNAILS';