export const CREATE_TRANSACTION = 'ADD_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const SET_TRANSACTIONS = 'SET_TRANSACTIONS';
export const SET_TO_BE_PROCCESSED_TRANSACTION =
  'SET_TO_BE_PROCCESSED_TRANSACTION';
export const SET_TRANSACTION_ACTION_MESSAGE = 'SET_TRANSACTION_ACTION_MESSAGE';
export const CLEAR_TRANSACTION_ACTION_MESSAGE =
  'CLEAR_TRANSACTION_ACTION_MESSAGE';
export const FETCH_UNREAD_TRANSACTIONS = 'FETCH_UNREAD_TRANSACTIONS';
export const FETCH_READ_TRANSACTIONS = 'FETCH_READ_TRANSACTIONS';
  
