export const CREATE_DIVISION = 'CREATE_DIVISION';
export const UPDATE_DIVISION = "UPDATE_DIVISION";
export const DELETE_DIVISION = "DELETE_DIVISION";
export const SET_DIVISIONS = 'SET_DIVISIONS';
export const SET_DIVISION_ACTION_RESULT = "SET_DIVISION_ACTION_RESULT";
