export const CREATE_TRANSACTION_IMAGE = "ADD_TRANSACTION_IMAGE";
export const UPDATE_TRANSACTION_IMAGE = "UPDATE_TRANSACTION_IMAGE";
export const DELETE_TRANSACTION_IMAGE = "DELETE_TRANSACTION_IMAGE";
export const SET_TRANSACTION_IMAGES = 'SET_TRANSACTION_IMAGES';