export const SET_TRANSACTION_STATUS_REPORT = 'SET_TRANSACTION_STATUS_REPORT';
export const CLEAR_FILTERED_REPORT_TRANSACTION =
  'CLEAR_FILTERED_REPORT_TRANSACTION';
export const TIME_RANGE_BASED_FILTERED_TRANSACTION =
  'TIME_RANGE_BASED_FILTERED_TRANSACTION';
export const TEXT_BASED_FILTERED_TRANSACTION =
  'TEXT_BASED_FILTERED_TRANSACTION';
export const DATE_CODE_BASED_FILTERED_TRANSACTION =
  'DATE_CODE_BASED_FILTERED_TRANSACTION';
export const CLEAR_TEXT_BASED_FILTERED_TRANSACTION =
  'CLEAR_TEXT_BASED_FILTERED_TRANSACTION';
export const CLEAR_DATE_CODE_BASED_FILTERED_TRANSACTION =
  'CLEAR_DATE_CODE_BASED_FILTERED_TRANSACTION';
export const LOAD_REPORT_LOADING =
  'LOAD_REPORT_LOADING';
  
