export const CREATE_SUBTYPE = 'CREATE_SUBTYPE';
export const UPDATE_SUBTYPE = 'UPDATE_SUBTYPE';
export const DELETE_SUBTYPE = 'DELETE_SUBTYPE';
export const SET_SUBTYPES = 'SET_SUBTYPES';
export const SET_ACTION_SUBTYPE_MESSAGE = 'SET_ACTION_SUBTYPE_MESSAGE';
export const CLEAR_SUBTYPE_ACTION_MESSAGE = 'CLEAR_SUBTYPE_ACTION_MESSAGE';
