export const CREATE_TYPE = 'CREATE_TYPE';
export const UPDATE_TYPE = 'UPDATE_TYPE';
export const DELETE_TYPE = 'DELETE_TYPE';
export const SET_TYPES = 'SET_TYPES';
export const SET_ACTION_TYPE_MESSAGE = 'SET_ACTION_TYPE_MESSAGE';
export const CLEAR_TYPE_ACTION_MESSAGE = 'ERROR_ACTION_TYPE_MESSAGE';
